[package]
name = "uniffi-swift-helpers"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
cargo_metadata = "0.19"
clap = { version = "4.5", features = ["derive"] }
serde_json = "1.0"
uniffi = "0.28.3"
uniffi_bindgen = "0.28.3"
