// swiftlint:disable all
{%- for module in modules_to_import %}
#if canImport({{ module }})
import {{ module }};
#endif
{%- endfor %}

// ==== Below are the original content generated by uniffi-rs ====
